package Class11_Constructors;

/*
 A default constructor is a constructor that is automatically provided by the Java compiler if no constructors are explicitly defined in a class.
 It has no parameters and initializes the object with default values.
 The default constructor is used to create an instance of a class without providing any arguments.
 If you define any constructor (with or without parameters) in a class, the default constructor will not be automatically generated by the compiler.
 In such cases, if you want to have a default constructor, you need to explicitly define it in your class.
 */


public class DefaultConstructorExample {
    // No constructors defined, so the default constructor will be provided by the compiler

    public void display() {
        System.out.println("This is a default constructor example.");
    }

    public static void main(String[] args) {
        // Creating an instance of DefaultConstructorExample using the default constructor
        DefaultConstructorExample example = new DefaultConstructorExample();
        example.display();
    }
}
